# Conda environment file for CI and deployment
name: nbdev2
channels:
  - conda-forge
dependencies:
  - python=3.9
  - python-graphviz
  - pandas
  - plotly
  - matplotlib
  - pillow # section 5.3 etc..
  - pytorch
  - nbformat
  - pip
