package:
  name: gtbook
  version: 0.0.7
source:
  sha256: ab1de94c738dc568afefe61d5321d108bc6e105d4bc7e7f1205fab13a4291533
  url: https://files.pythonhosted.org/packages/67/33/ad36e53f0e39d8c81a67e4bfbb03b7b0f89ff4b4aa1e56dddcd706ccde34/gtbook-0.0.7.tar.gz
about:
  dev_url: https://dellaert.github.io
  doc_url: https://dellaert.github.io
  home: https://dellaert.github.io
  license: Apache Software
  license_family: APACHE
  summary: test of nbdev
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - dellaert
requirements:
  host:
  - pip
  - python
  - packaging
  run:
  - pip
  - python
  - packaging
test:
  imports:
  - gtbook
