package:
  name: gtbook
  version: 0.0.9
source:
  sha256: 4d6de27effca5c783160244575116ef5a58ed62ebe07f48d49f11342d0cbf75f
  url: https://files.pythonhosted.org/packages/16/2c/8e869b7af3ad7eeb55d847e95faa6f8a07fda4035dac4c007fd2884c8d8a/gtbook-0.0.9.tar.gz
about:
  dev_url: https://gtbook.github.io/
  doc_url: https://gtbook.github.io/
  home: https://gtbook.github.io/
  license: Apache Software
  license_family: APACHE
  summary: Frank Dellaerts book support lib, made with nbdev
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - dellaert
requirements:
  host:
  - pip
  - python
  - packaging
  - python-graphviz
  run:
  - pip
  - python
  - packaging
  - python-graphviz
test:
  imports:
  - gtbook
