package:
  name: gtbook
  version: 0.0.3
source:
  sha256: 4af712bdbb0963a007a6202ba62ccf8a0caa784348e474d60e9390edae726488
  url: https://files.pythonhosted.org/packages/ff/6f/0b7eb1ab6d2079a08233c862671740be8fa1d906580a17a0af3ef218156e/gtbook-0.0.3.tar.gz
about:
  dev_url: https://dellaert.github.io
  doc_url: https://dellaert.github.io
  home: https://dellaert.github.io
  license: Apache Software
  license_family: APACHE
  summary: test of nbdev
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - dellaert
requirements:
  host:
  - pip
  - python
  - packaging
  run:
  - pip
  - python
  - packaging
test:
  imports:
  - gtbook
