package:
  name: gtbook
  version: 0.0.8
source:
  sha256: 6ee2105b5c96599ca229f421ebfc521a1bb50cc2738f98ec2e9d23c473a68bff
  url: https://files.pythonhosted.org/packages/2d/01/a7a4e30e17c3f52e002dd7e0686ef46f9a9b67bb11117d6da70609ccf717/gtbook-0.0.8.tar.gz
about:
  dev_url: https://gtbook.github.io/
  doc_url: https://gtbook.github.io/
  home: https://gtbook.github.io/
  license: Apache Software
  license_family: APACHE
  summary: Frank Dellaerts book support lib, made with nbdev
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - dellaert
requirements:
  host:
  - pip
  - python
  - packaging
  - python-graphviz
  run:
  - pip
  - python
  - packaging
  - python-graphviz
test:
  imports:
  - gtbook
