package:
  name: gtbook
  version: 0.0.30
source:
  sha256: fe7372cc2ed2c74b290c8c01083ff79b0ecf7e336d25f12bdb8704f94904b060
  url: https://files.pythonhosted.org/packages/d2/0d/62329fa396a77aa52f8a1c26e4b90af6549773fe8d315058192a14857cc0/gtbook-0.0.30.tar.gz
about:
  dev_url: https://gtbook.github.io/
  doc_url: https://gtbook.github.io/
  home: https://gtbook.github.io/
  license: Apache Software
  license_family: APACHE
  summary: Frank Dellaerts book support lib, made with nbdev
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - dellaert
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas
  - python-graphviz
  - matplotlib
  - pillow
  - pytorch
  run:
  - pip
  - python
  - packaging
  - pandas
  - python-graphviz
  - matplotlib
  - pillow
  - pytorch
test:
  imports:
  - gtbook
