package:
  name: gtbook
  version: 0.0.6
source:
  sha256: 8c2db238563f0ebdff90a0bb0c3091cfab017d1e441da03ef4f24d7b3b0e9614
  url: https://files.pythonhosted.org/packages/25/7c/ecb3cf72e8cc615bc1d0a3dcd2ddf40267bf0f7009314558ea2337469461/gtbook-0.0.6.tar.gz
about:
  dev_url: https://dellaert.github.io
  doc_url: https://dellaert.github.io
  home: https://dellaert.github.io
  license: Apache Software
  license_family: APACHE
  summary: test of nbdev
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - dellaert
requirements:
  host:
  - pip
  - python
  - packaging
  run:
  - pip
  - python
  - packaging
test:
  imports:
  - gtbook
