package:
  name: gtbook
  version: 0.0.4
source:
  sha256: 37d2f9c7da376ddccb3aeb5cd6ee0d2618d6a59ffe9b9f104dd45c7c7cd97a11
  url: https://files.pythonhosted.org/packages/96/1d/9a53987445f63d4c8446456c9ddd5ca9005baea55acec85cfb7a2f6f12c3/gtbook-0.0.4.tar.gz
about:
  dev_url: https://dellaert.github.io
  doc_url: https://dellaert.github.io
  home: https://dellaert.github.io
  license: Apache Software
  license_family: APACHE
  summary: test of nbdev
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - dellaert
requirements:
  host:
  - pip
  - python
  - packaging
  run:
  - pip
  - python
  - packaging
test:
  imports:
  - gtbook
