package:
  name: gtbook
  version: 0.0.15
source:
  sha256: 3f623df40c6078015543e087d02a6d6c8ce1232f162b38d07f26eaf623e2e91a
  url: https://files.pythonhosted.org/packages/37/be/b9376cc1a1e5c7fd64798c85a1cef080aaf3e0c44e150c91402ed18ec9d3/gtbook-0.0.15.tar.gz
about:
  dev_url: https://gtbook.github.io/
  doc_url: https://gtbook.github.io/
  home: https://gtbook.github.io/
  license: Apache Software
  license_family: APACHE
  summary: Frank Dellaerts book support lib, made with nbdev
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - dellaert
requirements:
  host:
  - pip
  - python
  - packaging
  - python-graphviz
  run:
  - pip
  - python
  - packaging
  - python-graphviz
test:
  imports:
  - gtbook
