package:
  name: gtbook
  version: 0.0.10
source:
  sha256: 7c82e0db58671f532cc59ab700583a88ef6a0d70d7559f72d86cde97814e94b9
  url: https://files.pythonhosted.org/packages/a2/23/5191aeefd925130e6af518190929b532240124591d3a57ff6db0ba2a3d09/gtbook-0.0.10.tar.gz
about:
  dev_url: https://gtbook.github.io/
  doc_url: https://gtbook.github.io/
  home: https://gtbook.github.io/
  license: Apache Software
  license_family: APACHE
  summary: Frank Dellaerts book support lib, made with nbdev
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - dellaert
requirements:
  host:
  - pip
  - python
  - packaging
  - python-graphviz
  run:
  - pip
  - python
  - packaging
  - python-graphviz
test:
  imports:
  - gtbook
